### ISSUE TITLE
use Processing transformation matrix

### ISSUE THREAD

**Issue by osresearch** [osresearch/vst#14]
Let the user call `translate()` and `rotate()` in Processing to adjust the position and orientation of the vectors.

**Comment by jacobjoaquin** [comment]
Matrix transforms are working in my fork. Use `modelX()` and `modelY()` in vector_point to support `translate()`, `scale()`, and `rotate()`.

Here's an example from VST.pde in the fireworksDemo.pde:

```
    int x = (int) (modelX(v.x, v.y, 0) * 2047 / width);
    int y = (int) (2047 - (modelY(v.x, v.y, 0) * 2047 / height));
```

**Comment by jacobjoaquin** [comment]
Re-implemented my original solution. Should work better now.

**Comment by osresearch** [comment]
This was merged, I think.
